reservedWords = {
    "error": "ERROR",
    "program": "PROGRAM",
    "procedure": "PROCEDURE",
    "type": "TYPE",
    "var": "VAR",
    "if": "IF",
    "then": "THEN",
    "else": "ELSE",
    "fi": "FI",
    "while": "WHILE",
    "do": "DO",
    "endwh": "ENDWH",
    "begin": "BEGIN",
    "end": "END",
    "read": "READ",
    "write": "WRITE",
    "array": "ARRAY",
    "of": "OF",
    "record": "RECORD",
    "return": "RETURN",
    "integer": "INTEGER",
    "char": "CHAR",
    "id": "ID",
    "intc": "INTC",
    "character": "CHARACTER",
}  # x

delimiters = {
    ".": "DOT",
    ":=": "ASSIGN",
    "=": "EQ",
    "<": "LT",
    "+": "PLUS",
    "-": "MINUS",
    "*": "TIMES",
    "/": "OVER",
    ":": "LPAREN",
    ",": "COMMA",
    "[": "LMIDPAREN",
    "]": "RMIDPAREN",
    "..": "UNDERRANGE",
    ";": "SEMI",
    "(": "LMIDPAREN",
    ")": "RMIDPAREN",
}  # 运算符、限界符
